### ISSUE TITLE
Fix sporadic TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by jviotti** [resin-io/resin-etcher#96]
This error seems to happen from time to time during burning:

```
TypeError: Cannot read property 'then' of undefined
    at burn (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:103:42)
    at fn (eval at <anonymous> (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:22559:15), <anonymous>:4:917)
    at callback (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:32807:17)
    at Scope.$eval (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:25246:28)
    at Scope.$apply (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:25346:25)
    at hero-progress-button.<anonymous> (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:32812:23)
    at defaultHandlerWrapper (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:12540:11)
    at hero-progress-button.eventHandler (file:///Users/jviotti/Projects/resin/resin-etcher/build/browser/app.js:12528:9)
```

**Comment by jviotti** [comment]
I can't reproduce this anymore. Maybe something like TrackJS (https://trackjs.com/for/angular/) can be a good thing to have for when thing happens again?

**Comment by jviotti** [comment]
PR integrating Etcher with TrackJS: https://github.com/resin-io/resin-etcher/pull/104

**Comment by jviotti** [comment]
This happens the the following conditions is true in `.burn()`, and therefore a promise is not returned:

```js
// Avoid writing more than once
if (self.isBurning()) {
  return;
}
```

https://github.com/resin-io/resin-etcher/blob/master/lib/browser/modules/image-writer.js#L182
